### ISSUE TITLE
Removing the Frost Effect

### ISSUE THREAD

**Issue by digitaluprising** [ionic-team/ionic-ion-frost#2]
Hey there,
In using this frost effect, I want to toggle the effect on and off. For example, when a popup opens, I'll add the frost directive to `<ion-view>`. When the popup closes, remove the frost directive.

I was thinking that there should be an event to remove the effect such as this:

```
$rootScope.$on('ionicFrosted.remove', function(){
  if(blurContent) {
    blurContent.remove();
  }
});
```

And then in my event handler, I'd broadcast the event: `$rootScope.$broadcast('ionicFrosted.remove');`

Is this the correct way of achieving this?

**Comment by palmthree-studio** [comment]
Hello, i'm interest to by a solution, have you found ?
Have a nice day !

**Comment by Ionitron** [comment]
Greetings @digitalu!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
